[package]
name = "testcrate"
version = "0.1.0"
authors = ["Aleksandr Orlenko <zxteam@protonmail.com>"]
edition = "2024"
publish = false

[features]
lua51 = []
lua52 = []
lua53 = []
lua54 = []
lua55 = []

[build-dependencies.lua-src]
path = ".."
features = ["ucid"]
