[package]
name = "lua-src"
version = "535.0.1+540b"
authors = ["Aleksandr Orlenko <zxteam@protonmail.com>"]
edition = "2018"
repository = "https://github.com/khvzak/lua-src-rs"
keywords = ["lua", "lua51", "lua52", "lua53", "lua54"]
readme = "README.md"
license = "MIT"
description = """
Sources of Lua 5.1/5.2/5.3/5.4(beta) and logic to build them.
"""

[workspace]
members = ["testcrate"]

[dependencies]
cc = "1.0"
